/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertificateInterface extends Interface {
  getFunction(
    nameOrSignature: "getCertificate" | "storeCertificate" | "verifyCertificate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeCertificate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export interface Certificate extends BaseContract {
  connect(runner?: ContractRunner | null): Certificate;
  waitForDeployment(): Promise<this>;

  interface: CertificateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCertificate: TypedContractMethod<[certNumber: string], [string], "view">;

  storeCertificate: TypedContractMethod<
    [certNumber: string, hashData: string],
    [void],
    "nonpayable"
  >;

  verifyCertificate: TypedContractMethod<
    [certNumber: string, hashData: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<[certNumber: string], [string], "view">;
  getFunction(
    nameOrSignature: "storeCertificate"
  ): TypedContractMethod<
    [certNumber: string, hashData: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<
    [certNumber: string, hashData: string],
    [boolean],
    "view"
  >;

  filters: {};
}
