/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SHMRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getHistory"
      | "getSHM"
      | "registerSHM"
      | "revokeSHM"
      | "updateOwner"
      | "verifySHM"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HistoryAdded"
      | "OwnerUpdated"
      | "SHMRegistered"
      | "SHMRevoked"
      | "SHMVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "getHistory", values: [string]): string;
  encodeFunctionData(functionFragment: "getSHM", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerSHM",
    values: [string, string, BytesLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "revokeSHM", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateOwner",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "verifySHM", values: [string]): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSHM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSHM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeSHM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifySHM", data: BytesLike): Result;
}

export namespace HistoryAddedEvent {
  export type InputTuple = [
    certNumber: string,
    action: string,
    actor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    certNumber: string,
    action: string,
    actor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    certNumber: string;
    action: string;
    actor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerUpdatedEvent {
  export type InputTuple = [
    certNumber: string,
    oldOwner: string,
    newOwner: string
  ];
  export type OutputTuple = [
    certNumber: string,
    oldOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    certNumber: string;
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SHMRegisteredEvent {
  export type InputTuple = [
    certNumber: string,
    documentHash: BytesLike,
    cid: string
  ];
  export type OutputTuple = [
    certNumber: string,
    documentHash: string,
    cid: string
  ];
  export interface OutputObject {
    certNumber: string;
    documentHash: string;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SHMRevokedEvent {
  export type InputTuple = [certNumber: string];
  export type OutputTuple = [certNumber: string];
  export interface OutputObject {
    certNumber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SHMVerifiedEvent {
  export type InputTuple = [certNumber: string];
  export type OutputTuple = [certNumber: string];
  export interface OutputObject {
    certNumber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SHMRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SHMRegistry;
  waitForDeployment(): Promise<this>;

  interface: SHMRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getHistory: TypedContractMethod<
    [certNumber: string],
    [
      [string[], string[], string[], string[], bigint[]] & {
        actions: string[];
        actors: string[];
        owners: string[];
        niks: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getSHM: TypedContractMethod<
    [certNumber: string],
    [[string, string, string, string, string, boolean, boolean, bigint]],
    "view"
  >;

  registerSHM: TypedContractMethod<
    [
      certNumber: string,
      cid: string,
      documentHash: BytesLike,
      ownerName: string,
      ownerNIK: string
    ],
    [void],
    "nonpayable"
  >;

  revokeSHM: TypedContractMethod<[certNumber: string], [void], "nonpayable">;

  updateOwner: TypedContractMethod<
    [certNumber: string, newOwner: string, newNIK: string],
    [void],
    "nonpayable"
  >;

  verifySHM: TypedContractMethod<[certNumber: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [certNumber: string],
    [
      [string[], string[], string[], string[], bigint[]] & {
        actions: string[];
        actors: string[];
        owners: string[];
        niks: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSHM"
  ): TypedContractMethod<
    [certNumber: string],
    [[string, string, string, string, string, boolean, boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerSHM"
  ): TypedContractMethod<
    [
      certNumber: string,
      cid: string,
      documentHash: BytesLike,
      ownerName: string,
      ownerNIK: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeSHM"
  ): TypedContractMethod<[certNumber: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOwner"
  ): TypedContractMethod<
    [certNumber: string, newOwner: string, newNIK: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifySHM"
  ): TypedContractMethod<[certNumber: string], [void], "nonpayable">;

  getEvent(
    key: "HistoryAdded"
  ): TypedContractEvent<
    HistoryAddedEvent.InputTuple,
    HistoryAddedEvent.OutputTuple,
    HistoryAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerUpdated"
  ): TypedContractEvent<
    OwnerUpdatedEvent.InputTuple,
    OwnerUpdatedEvent.OutputTuple,
    OwnerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SHMRegistered"
  ): TypedContractEvent<
    SHMRegisteredEvent.InputTuple,
    SHMRegisteredEvent.OutputTuple,
    SHMRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SHMRevoked"
  ): TypedContractEvent<
    SHMRevokedEvent.InputTuple,
    SHMRevokedEvent.OutputTuple,
    SHMRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SHMVerified"
  ): TypedContractEvent<
    SHMVerifiedEvent.InputTuple,
    SHMVerifiedEvent.OutputTuple,
    SHMVerifiedEvent.OutputObject
  >;

  filters: {
    "HistoryAdded(string,string,address,uint256)": TypedContractEvent<
      HistoryAddedEvent.InputTuple,
      HistoryAddedEvent.OutputTuple,
      HistoryAddedEvent.OutputObject
    >;
    HistoryAdded: TypedContractEvent<
      HistoryAddedEvent.InputTuple,
      HistoryAddedEvent.OutputTuple,
      HistoryAddedEvent.OutputObject
    >;

    "OwnerUpdated(string,string,string)": TypedContractEvent<
      OwnerUpdatedEvent.InputTuple,
      OwnerUpdatedEvent.OutputTuple,
      OwnerUpdatedEvent.OutputObject
    >;
    OwnerUpdated: TypedContractEvent<
      OwnerUpdatedEvent.InputTuple,
      OwnerUpdatedEvent.OutputTuple,
      OwnerUpdatedEvent.OutputObject
    >;

    "SHMRegistered(string,bytes32,string)": TypedContractEvent<
      SHMRegisteredEvent.InputTuple,
      SHMRegisteredEvent.OutputTuple,
      SHMRegisteredEvent.OutputObject
    >;
    SHMRegistered: TypedContractEvent<
      SHMRegisteredEvent.InputTuple,
      SHMRegisteredEvent.OutputTuple,
      SHMRegisteredEvent.OutputObject
    >;

    "SHMRevoked(string)": TypedContractEvent<
      SHMRevokedEvent.InputTuple,
      SHMRevokedEvent.OutputTuple,
      SHMRevokedEvent.OutputObject
    >;
    SHMRevoked: TypedContractEvent<
      SHMRevokedEvent.InputTuple,
      SHMRevokedEvent.OutputTuple,
      SHMRevokedEvent.OutputObject
    >;

    "SHMVerified(string)": TypedContractEvent<
      SHMVerifiedEvent.InputTuple,
      SHMVerifiedEvent.OutputTuple,
      SHMVerifiedEvent.OutputObject
    >;
    SHMVerified: TypedContractEvent<
      SHMVerifiedEvent.InputTuple,
      SHMVerifiedEvent.OutputTuple,
      SHMVerifiedEvent.OutputObject
    >;
  };
}
